export const META_COMPATIBILITY_MAP: Record<string, string[]> = {
  'OUTCOME_TRAFFIC': ['LINK_CLICKS', 'LANDING_PAGE_VIEWS', 'IMPRESSIONS'],
  'OUTCOME_AWARENESS': ['REACH', 'IMPRESSIONS', 'AD_RECALL_LIFT', 'THRUPLAY'],
  'OUTCOME_ENGAGEMENT': ['POST_ENGAGEMENT', 'REPLIES', 'THRUPLAY', 'CONVERSIONS'],
  'OUTCOME_LEADS': ['LEAD_GENERATION', 'QUALITY_LEAD', 'CONVERSIONS'],
  'OUTCOME_SALES': ['OFFSITE_CONVERSIONS', 'VALUE'],
  'OUTCOME_APP_PROMOTION': ['APP_INSTALLS', 'APP_EVENTS'],
};

export const CAMPAIGN_OBJECTIVES = Object.keys(META_COMPATIBILITY_MAP);

export const CALL_TO_ACTION_TYPES = [
    'NONE',
    'LEARN_MORE',
    'SHOP_NOW',
    'SIGN_UP',
    'CONTACT_US',
    'BOOK_TRAVEL',
    'GET_OFFER',
    'SUBSCRIBE',
    'DOWNLOAD',
    'MESSAGE_PAGE',
    'GET_QUOTE',
    'ORDER_NOW',
    'USE_APP',
];
