#!/bin/bash

# Quick Configuration Guide
# Shows what needs to be configured before the system works

echo "================================================================"
echo "          AUTOMATED LEAD PIPELINE - SETUP CHECKLIST"
echo "================================================================"
echo ""

# Check if agents exist
echo "✓ Step 1: ElevenLabs Agents"
echo "   Run: ./list-agents.sh"
echo "   Found agents:"
echo "   - SALLY: agent_5101kh4k6hxvezmsa2tbwp0y6mvs"
echo "   - quetzal: agent_1601kh502e9wfphv4q7chzct567x"
echo ""

echo "□ Step 2: Configure AWS Lambda Environment Variables"
echo "   Go to AWS Lambda Console and set these variables:"
echo ""
echo "   For transcriptWebhookHandler:"
echo "   ├─ FIREBASE_SERVICE_ACCOUNT_KEY=<your-firebase-json>"
echo "   ├─ FIREBASE_PROJECT_ID=admin-audit-3f2cd"
echo "   ├─ TRIGGER_OUTBOUND=false  (change to 'true' when ready)"
echo "   └─ OUTBOUND_LAMBDA_NAME=initiateOutboundCallHandler"
echo ""
echo "   For initiateOutboundCallHandler:"
echo "   ├─ ELEVENLABS_API_KEY=sk_908ed7e1b24e4327f378d08426b9751127808b99a4e641a7"
echo "   ├─ SALLY_AGENT_ID=agent_5101kh4k6hxvezmsa2tbwp0y6mvs"
echo "   └─ ACADEMY_PHONE=+13059293241"
echo ""
echo "   For markProcessedHandler:"
echo "   ├─ FIREBASE_SERVICE_ACCOUNT_KEY=<your-firebase-json>"
echo "   ├─ FIREBASE_PROJECT_ID=admin-audit-3f2cd"
echo "   └─ AUTH_TOKEN=123456789"
echo ""
echo "   For addLeadHandler:"
echo "   ├─ FIREBASE_SERVICE_ACCOUNT_KEY=<your-firebase-json>"
echo "   ├─ FIREBASE_PROJECT_ID=admin-audit-3f2cd"
echo "   └─ AUTH_TOKEN=123456789"
echo ""

echo "□ Step 3: Configure Student Intake Agent in ElevenLabs"
echo "   Agent: <Choose one of your agents>"
echo "   Add Custom Tool: 'add_lead'"
echo "   ├─ Name: add_lead"
echo "   ├─ URL: https://2cgrii72ke.execute-api.us-east-1.amazonaws.com/add-lead"
echo "   ├─ Method: POST"
echo "   ├─ Headers: Authorization: Bearer 123456789"
echo "   └─ Description: Save student lead to database"
echo ""
echo "   Add Webhook: End of Conversation"
echo "   └─ URL: https://2cgrii72ke.execute-api.us-east-1.amazonaws.com/transcript"
echo ""

echo "□ Step 4: Configure Sally (Outbound) Agent in ElevenLabs"
echo "   Agent: SALLY (agent_5101kh4k6hxvezmsa2tbwp0y6mvs)"
echo "   Add Webhook: End of Conversation"
echo "   └─ URL: https://2cgrii72ke.execute-api.us-east-1.amazonaws.com/transcript"
echo ""

echo "□ Step 5: Test the Pipeline"
echo "   Test 1: Create a lead"
echo "   $ curl -X POST https://2cgrii72ke.execute-api.us-east-1.amazonaws.com/add-lead \\"
echo "     -H \"Authorization: Bearer 123456789\" \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"name\":\"Test\",\"phone\":\"+15555551234\",\"clase\":\"BJJ\"}'"
echo ""
echo "   Test 2: Trigger transcript (with TRIGGER_OUTBOUND=false)"
echo "   $ curl -X POST https://2cgrii72ke.execute-api.us-east-1.amazonaws.com/transcript \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"transcript\":\"Test call\"}'"
echo ""
echo "   Test 3: Check CloudWatch logs"
echo "   └─ Should see: 'Found X unprocessed leads'"
echo "   └─ Should see: 'SKIPPED - TRIGGER_OUTBOUND not enabled'"
echo ""

echo "□ Step 6: Enable Automation"
echo "   In AWS Lambda Console:"
echo "   transcriptWebhookHandler → Environment variables"
echo "   └─ Change TRIGGER_OUTBOUND from 'false' to 'true'"
echo ""

echo "================================================================"
echo "                     CURRENT STATUS"
echo "================================================================"
echo "Stack: SALLY"
echo "Region: us-east-1"
echo "Base URL: https://2cgrii72ke.execute-api.us-east-1.amazonaws.com"
echo "Academy Phone: +13059293241"
echo ""
echo "Lambda Functions Deployed: 8"
echo "├─ addLeadHandler"
echo "├─ transcriptWebhookHandler"
echo "├─ initiateOutboundCallHandler"
echo "├─ markProcessedHandler"
echo "├─ getScheduleHandler"
echo "├─ updateScheduleHandler"
echo "├─ getLeadsHandler"
echo "└─ conversationInitHandler"
echo ""
echo "================================================================"
echo "For detailed instructions, see:"
echo "  - DEPLOYMENT.md (full deployment guide)"
echo "  - COMPLETION.md (architecture and summary)"
echo "  - CLI-README.md (agent CLI helpers)"
echo "================================================================"
